language: node_js
node_js: node
services: 
  - postgresql
before_script:
  - psql -c 'create database jobsearchtest;' -U postgres
install: 
  - yarn
  - yarn global add typescript
  - yarn global add ts-node
  - yarn build:rest-server
  - yarn env
  - yarn db:setup:rest-server
script:
  - yarn lint:rest-server
  - yarn start:rest-server &
  - sleep 10
  - yarn run test:rest-server
