language: node_js
node_js: node
services: 
  - postgresql
before_install:
  - psql -c 'CREATE DATABASE jobsearchtest;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD '';" -U postgres
  - psql -c 'ALTER USER root WITH SUPERUSER;' -U postgres
install: 
  - yarn
  - yarn global add typescript
  - yarn global add ts-node
  - yarn build:rest-server
  - yarn env
  - yarn db:setup:rest-server
script:
  - yarn lint:rest-server
  - yarn start:rest-server &
  - sleep 10
  - jest user_joiValidation.test.ts
  - sleep 10
  - jest user_integration.test.ts
  - sleep 10
  - jest project_integration.test.ts
  - sleep 10
  - jest project_joiValidation.test.ts
  - sleep 10
  - jest auth_joiValidation.test.ts
