language: node_js
node_js: node
services: 
  - postgresql
before_install:
  - psql -c 'CREATE DATABASE jobsearchtest;' -U postgres
  - psql -c "CREATE USER root WITH PASSWORD '';" -U postgres
  - psql -c 'ALTER USER root WITH SUPERUSER;' -U postgres
install: 
  - yarn
  - yarn global add typescript
  - yarn global add ts-node
  - yarn global add jest
  - yarn build:rest-server
  - yarn env
  - yarn db:setup:rest-server
script:
  - yarn lint:rest-server
  - yarn start:rest-server &
  - sleep 10
  - jest rest-server/components/user/__tests__/user_joiValidation.test.ts 
  - jest rest-server/components/user/__tests__/user_integration.test.ts 
  - jest rest-server/components/project/__tests__/project_integration.test.ts 
  - jest rest-server/components/project/__tests__/project_joiValidation.test.ts
  - jest rest-server/components/auth/__tests__/auth_joiValidation.test.ts
